### ISSUE TITLE
bigquery.storage.v1beta2 JsonStreamWriter client crashes forever with "StatusRuntimeException FAILED_PRECONDITION ... Received unexpected EOS on empty DATA frame from server"

### ISSUE THREAD

**Issue by rodrigo-loza-mojix** [googleapis/java-bigquerystorage#1392]
#### Environment details

1. API -> bigquery.storage.v1beta2 JsonStreamWriter 
2. Running in docker image -> registry.access.redhat.com/ubi8/ubi-minimal:8.4 (Quarkus jvm standard Dockerfile)
3. Java version: 11
4. bigquerystorage version(s): 
- groupId:com.google.api.grpc 
- artifactId: proto-google-cloud-bigquerystorage-v1beta2
- version 0.125.2

#### Steps to reproduce

  1. Create a JsonStreamWriter as documented in the examples. 
  2. Continuously write data with the build JsonStreamWriter for some hours. 
  3. After 8-12 hours of writing. A StatusRuntimeException  INTERNAL: Received unexpected EOS on empty DATA frame from server pops up. Which is unrecoverable and unretriable.

#### Code example

```java
ServiceAccountCredentials serviceAccountCredentials = ServiceAccountCredentials
                .fromStream(new FileInputStream(...));
FixedCredentialsProvider.create(serviceAccountCredentials);
BigQueryWriteSettings.newBuilder().setCredentialsProvider(fixedCredentialsProvider).build()

WriteStream stream = WriteStream.newBuilder().setType(WriteStream.Type.COMMITTED).build();
CreateWriteStreamRequest createWriteStreamRequest = CreateWriteStreamRequest.newBuilder()
                .setParent(parentTable.toString())
                .setWriteStream(stream)
                .build();
BigQueryWriteClient.createWriteStream(createWriteStreamRequest);

JsonStreamWriter.newBuilder(writeStream.getName(), writeStream.getTableSchema())
                .setCredentialsProvider(fixedCredentialsProvider)
                .build();

ApiFuture<AppendRowsResponse> future = metadataJsonStreamWriter.append(jsonArray);
future.get(futureMetadataWriteTimeout, TimeUnit.MILLISECONDS);
```

#### Stack trace
```
 [com.goo.clo.big.sto.v1b.StreamWriterV2] (grpc-default-executor-3) Received done callback. Stream: projects/XXXX/datasets/XXXXXX/tables/metadata/streams/Cic2NDAxZmI1NS0wMDAwLTIyM2UtYWI0My0xNGMxNGVmMzdmYTQ6czI Final status: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-5) Cleanup starts. Stream: projects/XXXXXXX/datasets/XXXXXXX/tables/metadata/streams/Cic2NDAxZmI1NS0wMDAwLTIyM2UtYWI0My0xNGMxNGVmMzdmYTQ6czI
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-5) Waiting for done callback from stream connection. Stream: projects/XXXXXXX/datasets/XXXXXXX/tables/metadata/streams/Cic2NDAxZmI1NS0wMDAwLTIyM2UtYWI0My0xNGMxNGVmMzdmYTQ6czI
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-5) Stream connection is fully closed. Cleaning up inflight requests. Stream: projects/XXXXXXX/datasets/XXXXX/tables/metadata/streams/Cic2NDAxZmI1NS0wMDAwLTIyM2UtYWI0My0xNGMxNGVmMzdmYTQ6czI
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-5) Cleaning 0 inflight requests with error: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-5) Append thread is done. Stream: projects/saas-analytics-io/datasets/kafka_v1data1/tables/metadata/streams/Cic2NDAxZmI1NS0wMDAwLTIyM2UtYWI0My0xNGMxNGVmMzdmYTQ6czI
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (grpc-default-executor-4) Received done callback. Stream: projects/saas-analytics-io/datasets/kafka_v1data1/tables/udf/streams/Cic2M2VlZjcyMS0wMDAwLTIzN2MtYWE2OC01ODI0MjliYmVhZDg6czE Final status: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-7) Cleanup starts. Stream: projects/XXXXXX/datasets/kafka_v1data1/tables/XXXXX/streams/Cic2M2VlZjcyMS0wMDAwLTIzN2MtYWE2OC01ODI0MjliYmVhZDg6czE
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-7) Waiting for done callback from stream connection. Stream: projects/XXXXXXX/datasets/XXXXXX/tables/udf/streams/Cic2M2VlZjcyMS0wMDAwLTIzN2MtYWE2OC01ODI0MjliYmVhZDg6czE
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-7) Stream connection is fully closed. Cleaning up inflight requests. Stream: projects/XXXXXXX/datasets/XXXXXX/tables/udf/streams/Cic2M2VlZjcyMS0wMDAwLTIzN2MtYWE2OC01ODI0MjliYmVhZDg6czE
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-7) Cleaning 0 inflight requests with error: com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
INFO  [com.goo.clo.big.sto.v1b.StreamWriterV2] (Thread-7) Append thread is done. Stream: projects/XXXXX/datasets/XXXXXX/tables/udf/streams/Cic2M2VlZjcyMS0wMDAwLTIzN2MtYWE2OC01ODI0MjliYmVhZDg6czE
INFO  [com.moj.yte.big.big.con.JsonStreamWriterService] (pool-10-thread-2) Writing 1 blinks.
INFO  [com.moj.yte.big.big.con.JsonStreamWriterService] (pool-10-thread-2) Retrying failed blink. Retries 2: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Stream is closed due to com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server


2021-11-02 01:54:09,436 INFO  [com.moj.yte.big.big.con.JsonStreamWriterService] (pool-10-thread-1) Retrying failed blink. Retries 0: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Stream is closed due to com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:421)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:61)
	at com.mojix.ytem.bigqueryinjector.bigquery.controller.JsonStreamWriterService.writeMetadataBatch(JsonStreamWriterService.java:70)
	at com.mojix.ytem.bigqueryinjector.bigquery.controller.JsonStreamWriterService.writeCollectionBatch(JsonStreamWriterService.java:45)
	at com.mojix.ytem.bigqueryinjector.bigquery.controller.JsonStreamWriterService_ClientProxy.writeCollectionBatch(JsonStreamWriterService_ClientProxy.zig:131)
	at com.mojix.ytem.bigqueryinjector.injector.common.controller.InjectorController.lambda$buildJsonWriterStreamRunnable$0(InjectorController.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Stream is closed due to com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
	at com.google.cloud.bigquery.storage.v1beta2.StreamWriterV2.appendInternal(StreamWriterV2.java:263)
	at com.google.cloud.bigquery.storage.v1beta2.StreamWriterV2.append(StreamWriterV2.java:234)
	at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.append(JsonStreamWriter.java:114)
	at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.append(JsonStreamWriter.java:89)
	at com.mojix.ytem.bigqueryinjector.bigquery.controller.JsonStreamWriterService.writeMetadataBatch(JsonStreamWriterService.java:69)
```

#### External references such as API reference guides

- https://cloud.google.com/bigquery/docs/write-api#write_data_using_the_jsonstreamwriter

Thanks!

**Comment by yirutang** [comment]
We will be adding automatic reconnection feature to v1 client lib soon. 
For current v1 and v1beta2, the client library cannot reconnect itself. So on such error, you can just recreate a Writer.

**Comment by yirutang** [comment]
Server side could close the stream due to task restart, that is expected.

**Comment by rodrigo-loza-mojix** [comment]
Got it, thanks so much. 

I am currently catching the exception that triggers a liveness restart on the container. But it doesn't look very clean.

**Comment by dinvlad** [comment]
Has the automatic reconnection feature been added? It seems to be getting a background `java.util.concurrent.ExecutionException: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: Deadline expired before operation could complete` after a few days of streaming, and doesn't auto-reconnect afterwards, leading to a deadlock on the inserts..

**Comment by yirutang** [comment]
Yes, it should be available in latest v1 library. What is your full stack trace?

**Comment by dinvlad** [comment]
Unfortunately, I haven't caught it - will do later (the error is rare, so will take some time). Should I create a separate issue for it then?

**Comment by yirutang** [comment]
Sure, but I don't know how to follow up without a stack trace.

**Comment by yirutang** [comment]
We recently fixed a stuck issue because we didn't get a DoneCallback ever as expected. We added some timeout on the wait.
