### ISSUE TITLE
BQTableSchemaToProtoDescriptor missing BigNumeric mapping

### ISSUE THREAD

**Issue by slilichenko** [googleapis/java-bigquerystorage#1571]
#### Steps to reproduce
Attempt to write to a table with a BigNumeric column fails with :
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Builder.setType(DescriptorProtos.java:13488)
	at com.google.cloud.bigquery.storage.v1beta2.BQTableSchemaToProtoDescriptor.convertBQTableFieldToProtoField(BQTableSchemaToProtoDescriptor.java:149)
	at com.google.cloud.bigquery.storage.v1beta2.BQTableSchemaToProtoDescriptor.convertBQTableSchemaToProtoDescriptorImpl(BQTableSchemaToProtoDescriptor.java:113)
	at com.google.cloud.bigquery.storage.v1beta2.BQTableSchemaToProtoDescriptor.convertBQTableSchemaToProtoDescriptor(BQTableSchemaToProtoDescriptor.java:72)
	at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.<init>(JsonStreamWriter.java:62)
	at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter.<init>(JsonStreamWriter.java:39)
	at com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter$Builder.build(JsonStreamWriter.java:333)
	at com.google.solutions.direct.WriteToBigQuery.appendRows(WriteToBigQuery.java:160)
```

**Comment by dark0dave** [comment]
I was able to write with:
```
                TableFieldSchema.newBuilder()
                    .setType(BIGNUMERIC)
                    .setName("d")
                    .setMode(NULLABLE)
                    .build())
```
data: {"d":"3.3"}

**Comment by dark0dave** [comment]
No, and I don't assume that. Most of the use-cases I am familiar with you provide the schema. I don't assume anything.

**Comment by dark0dave** [comment]
When something implicit is not working, be explicit so the saying goes anyways.

**Comment by slilichenko** [comment]
In my opinion, if the schema is not provided explicitly and the code breaks with NPE - it's a bug. A specific example of where it's broken is a Beam's BigQueryIO connector constructed without `withSchema()` method.

**Comment by yirutang** [comment]
Please use v1 client.

**Comment by slilichenko** [comment]
Thank you Yiru - it worked.
