### ISSUE TITLE
Getting FAILED_PRECONDITION: Connection is closed due to com.google.api.gax.rpc.InternalException

### ISSUE THREAD

**Issue by subham611** [googleapis/java-bigquerystorage#2078]
I have been using java service which write records to BQ using storage api. Its been running fine for almost a week and then suddenly i see below FAILED_PRECONDITION in application log.

```
java.lang.RuntimeException: com.google.cloud.bigquery.storage.v1.Exceptions$StreamWriterClosedException: FAILED_PRECONDITION: Connection is closed due to com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: A retriable error could not be retried due to Extensible Stubs memory limits for streams (see go/xs-retries-memory-limit-reached) (old status: RPC::STREAM_BROKEN: Connection to server broken (OnChannelError))
	at DataWriter$AppendCompleteCallback.onFailure(DataWriter.java:160)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1105)
	at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:62)
	at DataWriter.append(DataWriter.java:92)
	at DataWriter$AppendCompleteCallback.onFailure(DataWriter.java:139)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:761)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1105)
	at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:62)
	at DataWriter.append(DataWriter.java:92)
	at DataWriter$AppendCompleteCallback.onFailure(DataWriter.java:139)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:92)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:74)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:51)
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker.cleanupInflightRequests(ConnectionWorker.java:835)
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker.appendLoop(ConnectionWorker.java:739)
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker.access$000(ConnectionWorker.java:65)
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker$1.run(ConnectionWorker.java:299)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.cloud.bigquery.storage.v1.Exceptions$StreamWriterClosedException: FAILED_PRECONDITION: Connection is closed due to com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: A retriable error could not be retried due to Extensible Stubs memory limits for streams (see go/xs-retries-memory-limit-reached) (old status: RPC::STREAM_BROKEN: Connection to server broken (OnChannelError))
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker.appendInternal(ConnectionWorker.java:439)
	at com.google.cloud.bigquery.storage.v1.ConnectionWorker.append(ConnectionWorker.java:383)
	at com.google.cloud.bigquery.storage.v1.StreamWriter$SingleConnectionOrConnectionPool.append(StreamWriter.java:154)
	at com.google.cloud.bigquery.storage.v1.StreamWriter.append(StreamWriter.java:426)
	at com.google.cloud.bigquery.storage.v1.JsonStreamWriter.append(JsonStreamWriter.java:234)
	at com.google.cloud.bigquery.storage.v1.JsonStreamWriter.append(JsonStreamWriter.java:116)
	at DataWriter.append(DataWriter.java:91)
	... 24 more

```

This is my build.gradle dependency for storage write api

implementation platform('com.google.cloud:libraries-bom:26.11.0')
implementation 'com.google.cloud:google-cloud-bigquerystorage'
implementation 'com.google.cloud:google-cloud-bigquery'

I am using spring boot version 2.7.2

```
Here is code snippet for BQ default storage api client:
BQClient.java

public void loadData(JSONArray jsonArray, String tableName)
            throws DescriptorValidationException, InterruptedException, IOException {

        TableName parentTable = TableName.of(projectId, bqDataSetName, tableName);
        DataWriter writer = bqStreamRepository.getDataWriter(parentTable);

        writer.append(new AppendContext(jsonArray, 0));
        int size = jsonArray.length();
        log.info("Appended {} records successfully.", size);
    }
```

DataWriter code is same as mentioned here [storage api java client](https://cloud.google.com/bigquery/docs/write-api-streaming#at-least-once:~:text=exactly%2Donce%20guarantees.-,Use%20the%20default%20stream%20for%20at%2Dleast%2Donce%20semantics,-If%20your%20application)

We are managing DataWriter objects in a hashMap, this to have a single DataWriter instance per table for project lifecycle.
Code:

BqStreamRepository.java

 ```
 private Map<String, DataWriter> dataWriterMap = new ConcurrentHashMap<>();

     public DataWriter getDataWriter(TableName tableName) throws Descriptors.DescriptorValidationException, IOException, InterruptedException {
         DataWriter dataWriter = dataWriterMap.getOrDefault(tableName.getTable(), null);
         if(dataWriter == null) {
             synchronized (this) {
                 if(dataWriter == null) {
                     dataWriter = new DataWriter();
                     // One time initialization for the worker.
                     dataWriter.initialize(tableName);
                     dataWriterMap.put(tableName.getTable(), dataWriter);
                 }
             }
         }
         return dataWriter;
     }

     @PreDestroy
    public void cleanUp() {
         // Final cleanup for the stream during worker teardown.
         log.info("Cleaning up data writer");
         dataWriterMap.forEach((tableName, dataWriter) -> dataWriter.cleanup());
     }
```

**Comment by Neenu1995** [comment]
@yirutang PTAL

**Comment by yirutang** [comment]
Could you add FAILED_PRECONDITION to your retry code?

**Comment by subham611** [comment]
I have already added FAILED_PRECONDITION in retry code

**Comment by yirutang** [comment]
This is due to some wrong settings in our router layer to retry with estub which will never succeed. We are aware of this and trying to fix the issue but it usually takes quite a while to fix issues in routers. 

Thanks.
