### ISSUE TITLE
JsonStreamWriter setDefaultMissingValueInterpretation doesn't seem to work

### ISSUE THREAD

**Issue by fqaiser94** [googleapis/java-bigquerystorage#2265]
I'm trying to make use of Default Value Expressions when writing rows to BigQuery via the Storage Write API. 
Specifically, I have a row that is missing a field that is defined in the TableSchema. 
However, this field that is missing in my row has a default value expression defined for it in the TableSchema. 
As far as I understand, I believe I should be able to write the row as long as I've configured my `JsonStreamWriter` with                             `.setDefaultMissingValueInterpretation(AppendRowsRequest.MissingValueInterpretation.DEFAULT_VALUE)`
and then BigQuery should be able to fill in the value of the missing field by using the default value expression defined in the table schema. 
However, `JsonStreamWriter` keeps throwing an error whenever I try to send such a row. 

# Environment details

1. Specify the API: JsonStreamWriter
2. OS type and version: MacOS Monterey (12.6.5)
3. Java version: openjdk 11.0.14.1 2022-02-08 LTS

# Steps to reproduce

I've created a [mini Java (Maven) project](https://github.com/fqaiser94/reproduce-bigquery-json-stream-writer-issue) that should make it easy to reproduce the issue.  
Feel free to open a PR against the repo if the problem is in my code. 

# Code example

Assuming I have a table like this: 

```java
    static TableReference TABLE_REFERENCE =
            new TableReference()
                    .setProjectId(PROJECT_ID)
                    .setDatasetId(DATASET_ID)
                    .setTableId(TABLE_ID);

    static String STRING_FIELD_NAME = "string_col";
    static String STRING_WITH_DEFAULT_VALUE_FIELD_NAME = "string_col_with_default_value";

    static TableSchema TABLE_SCHEMA = new TableSchema().setFields(ImmutableList.of(
            new TableFieldSchema().setName(STRING_FIELD_NAME).setType("STRING").setMode("REQUIRED"),
            // notice how we've set a default value expression for this field so I should be able to send rows missing this field
            new TableFieldSchema().setName(STRING_WITH_DEFAULT_VALUE_FIELD_NAME).setType("STRING").setMode("REQUIRED").setDefaultValueExpression("'world'")
    ));

    static Table TABLE = new Table().setTableReference(TABLE_REFERENCE).setSchema(TABLE_SCHEMA);
```

Then I want to be able to do something like this: 

```java
            JsonStreamWriter streamWriter =
                    JsonStreamWriter.newBuilder(
                                    WriteStreamName.of(PROJECT_ID, DATASET_ID, TABLE_ID, "_default").toString(),
                                    bigQueryWriteClient)
                            // I've made sure to setDefaultMissingValueInterpretation correctly AFAICT
                            .setDefaultMissingValueInterpretation(AppendRowsRequest.MissingValueInterpretation.DEFAULT_VALUE)
                            .build();

            // Able to successfully send a JSON object that has all the fields defined in TABLE_SCHEMA
            streamWriter.append(new JSONArray().put(
                    new JSONObject().put(STRING_FIELD_NAME, "foo").put(STRING_WITH_DEFAULT_VALUE_FIELD_NAME, "bar"))).get();

            // Done this as well even though it should not be necessary since I've already configured the default behaviour on line 83
            streamWriter.setMissingValueInterpretationMap(Collections.singletonMap(
                    STRING_WITH_DEFAULT_VALUE_FIELD_NAME,
                    AppendRowsRequest.MissingValueInterpretation.DEFAULT_VALUE));

            // Throws an error if I try to send a JSON object that is missing a field even though it has a DefaultValueExpression defined
            // I don't understand why this doesn't work. 
            streamWriter.append(new JSONArray().put(
                    new JSONObject().put(STRING_FIELD_NAME, "hello"))).get();
```

Produces the following stack trace

```
Oct. 05, 2023 9:49:42 P.M. com.google.cloud.bigquery.storage.v1.ConnectionWorker resetConnection
INFO: Start connecting stream: projects/flink-bq-writer/datasets/temp/tables/temp3/streams/_default id: 7fe0c63f-b58a-4875-93ba-9e7b1ff27567
Oct. 05, 2023 9:49:42 P.M. com.google.cloud.bigquery.storage.v1.ConnectionWorker resetConnection
INFO: Finish connecting stream: projects/flink-bq-writer/datasets/temp/tables/temp3/streams/_default id: 7fe0c63f-b58a-4875-93ba-9e7b1ff27567
Exception in thread "main" com.google.cloud.bigquery.storage.v1.Exceptions$AppendSerializationError: INVALID_ARGUMENT: Append serialization failed for writer: projects/flink-bq-writer/datasets/temp/tables/temp3/streams/_default
	at com.google.cloud.bigquery.storage.v1.SchemaAwareStreamWriter.append(SchemaAwareStreamWriter.java:210)
	at com.google.cloud.bigquery.storage.v1.SchemaAwareStreamWriter.append(SchemaAwareStreamWriter.java:123)
	at com.google.cloud.bigquery.storage.v1.JsonStreamWriter.append(JsonStreamWriter.java:62)
	at com.fq.ReproduceIssue.main(ReproduceIssue.java:97)
```

Should this work? Or am I misinterpreting something here? 

# Sort-of work-around

The only way I can something close to working is if I explicitly specify the `TableSchema` when creating a JsonStreamWriter and specifically exclude the `STRING_WITH_DEFAULT_VALUE_FIELD_NAME` as shown below (or for a full example, see [this PR](https://github.com/fqaiser94/reproduce-bigquery-json-stream-writer-issue/pull/1/files)). 
```java
            JsonStreamWriter streamWriter =
                    JsonStreamWriter.newBuilder(
                                    WriteStreamName.of(PROJECT_ID, DATASET_ID, TABLE_ID, "_default").toString(),
                                    // explicitly specify schema specifically excluding STRING_WITH_DEFAULT_VALUE_FIELD_NAME
                                    com.google.cloud.bigquery.storage.v1.TableSchema.newBuilder()
                                            .addFields(com.google.cloud.bigquery.storage.v1.TableFieldSchema.newBuilder()
                                                    .setName(STRING_FIELD_NAME).setType(com.google.cloud.bigquery.storage.v1.TableFieldSchema.Type.STRING)
                                                    .setMode(com.google.cloud.bigquery.storage.v1.TableFieldSchema.Mode.REQUIRED)
                                                    .build())
                                            // .addFields(com.google.cloud.bigquery.storage.v1.TableFieldSchema.newBuilder()
                                            //         .setName(STRING_WITH_DEFAULT_VALUE_FIELD_NAME).setType(com.google.cloud.bigquery.storage.v1.TableFieldSchema.Type.STRING)
                                            //         .setMode(com.google.cloud.bigquery.storage.v1.TableFieldSchema.Mode.REQUIRED)
                                            //         .build())
                                            .build(),
                                    bigQueryWriteClient)
                            // I don't even need this anymore
                            // .setDefaultMissingValueInterpretation(AppendRowsRequest.MissingValueInterpretation.DEFAULT_VALUE)
                            .build();

            // This does work correctly now!
            streamWriter.append(new JSONArray().put(
                    new JSONObject().put(STRING_FIELD_NAME, "hello"))).get();

            // However, I can no longer send messages which have all the fields present. This throws an error now.
            streamWriter.append(new JSONArray().put(
                    new JSONObject().put(STRING_FIELD_NAME, "foo").put(STRING_WITH_DEFAULT_VALUE_FIELD_NAME, "bar"))).get();
```

 But then I can't send messages which have all the fields defined :/ 

Ideally I only want to create one JsonStreamWriter that can handle both: 
- messages that have all the fields present 
- AND messages that are missing fields with defaultValueExpressions defined in the TableSchema

I thought that's what `setDefaultMissingValueInterpretation` would allow me to do but it doesn't seem to be the case. 
Again, please feel free to correct my understanding if I'm mistaken

**Comment by Neenu1995** [comment]
@GaoleMeng PTAL.

**Comment by yirutang** [comment]
The feature should have been fully rolled out now, please try again.

Sorry about the problem.
